name = "db0worker"
main = "mainWorker.js"
compatibility_date = "2025-10-21"

# optional Node.js compat
compatibility_flags = ["nodejs_compat"]

# Do NOT include real database info here
# We'll use secrets instead
[[d1_databases]]
binding = "DB"
database_name = "anime_info"
database_id = "bc1bcde4-5db8-4860-a965-7fcb7a427475"

[triggers]
crons = ["0 * * * *"]

[vars]
LOG_LEVEL = "info"
