name = "erenworld-auto-db"
main = "mainWorker.js"
compatibility_date = "2025-10-21"

# optional Node.js compat
compatibility_flags = ["nodejs_compat"]

# Do NOT include real database info here
# We'll use secrets instead
[[d1_databases]]
binding = "DB"
database_name = "anime_info"
database_id = "4ea68080-166a-4819-b467-0255c6e044cc"

[triggers]
crons = ["0 * * * *"]

[vars]
LOG_LEVEL = "info"
